### ISSUE TITLE
关于复赛

### ISSUE THREAD

**Issue by hyoukaLaw** [xyh1756/CodeCraft2021#1]
大佬您好！从您的初赛代码和解题思路中学到了很多，如果可以能不能将复赛代码和解题思路也一并分享，十分感谢！

**Comment by xyh1756** [comment]
复赛代码其实在second分支有的，你切换一下。算法上其实初赛和复赛没啥区别，我那个解题思路已经是复赛的最终版整理出来的了，没啥不一样的。: )

**Comment by hyoukaLaw** [comment]
ok，谢谢！
